package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2018_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the vcsRoot with id = 'HttpsGithubComSpringProjectsSpringPetclinicRefsHeadsMaster'
accordingly, and delete the patch script.
*/
changeVcsRoot(RelativeId("HttpsGithubComSpringProjectsSpringPetclinicRefsHeadsMaster")) {
    val expected = GitVcsRoot({
        id("HttpsGithubComSpringProjectsSpringPetclinicRefsHeadsMaster")
        name = "https://github.com/spring-projects/spring-petclinic#refs/heads/master"
        url = "https://github.com/spring-projects/spring-petclinic"
    })

    check(this == expected) {
        "Unexpected VCS root settings"
    }

    (this as GitVcsRoot).apply {
        name = "spring-petclinit"
        url = "https://github.com/PortManHead/spring-petclinic"
    }

}
